### PR TITLE
Getting started with unit tests

### PR DESCRIPTION
**Pull request by r48patel**

### CODE REVIEW

**Comment by r48patel** [comment]
jenkins retest this please

**Comment by r48patel** [comment]
jenkins test this please

**Comment by r48patel** [comment]
jenkins test this please

**Comment by r48patel** [comment]
okay to test

**Comment by r48patel** [comment]
jenkins test this please

**Comment by r48patel** [comment]
jenkins test this please

**Comment by r48patel** [comment]
retest this please

**Comment by r48patel** [comment]
retest this please

**Comment by fahdsiddiqui** [comment]
LGTM 👍

**Pull request merged**
