### PR TITLE
Added support for environment variables

### PR DESCRIPTION
**Pull request by aelmhorst**
Please consider this pull request, adding support for specifying environment variables for the processes that are started. I have tested this locally in my build and it allows for me to specify env vars when starting a process.

Also, added .gitignore entries to ignore Eclipse .classpath and .settings

### CODE REVIEW

**Comment by fahdsiddiqui** [comment]
Thank you for your contribution. Will test it out, and let you know soon.

**Comment by aelmhorst** [comment]
Here's a sample pom that we're using to demonstrate...

```
<plugin>
	<groupId>com.bazaarvoice.maven.plugins</groupId>
	<artifactId>process-exec-maven-plugin</artifactId>
	<executions>
		<!--Start the  process for integration tests -->
		<execution>
			<id>myApp process</id>
			<phase>pre-integration-test</phase>
			<goals>
				<goal>start</goal>
			</goals>
			<configuration>
				<name>myApp</name>
				<workingDir></workingDir>
				<waitForInterrupt>false</waitForInterrupt>
				<healthcheckUrl>http://localhost:6000/ops/hello</healthcheckUrl>
				<environment>
					<PORT>6000</PORT>
					<ENV_VAR2>FOO</ENV_VAR2>
					<ENV_VAR3>TEST</ENV_VAR3>
				</environment>
				<arguments>
					<argument>sh</argument>
					<argument>./bin/myapp</argument>
				</arguments>
			</configuration>
		</execution>
		<!--Stop all processes in reverse order -->
		<execution>
			<id>stop-all</id>
			<phase>post-integration-test</phase>
			<goals>
				<goal>stop-all</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

**Comment by fahdsiddiqui** [comment]
retest this please

**Comment by aelmhorst** [comment]
Hello, Is there anything I can do to help push this pull request along?

**Pull request closed without merging**
